# Generated by Django 3.2.9 on 2021-11-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.DateField(),
        ),
    ]
