# Generated by Django 3.2.9 on 2021-11-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0006_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Age',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
