# Generated by Django 3.2.9 on 2021-11-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0007_auto_20211119_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
