# Generated by Django 3.2.9 on 2021-11-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0010_alter_dob_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dob',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Age',
            field=models.DateField(),
        ),
    ]
