# Generated by Django 3.2.9 on 2021-11-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0012_alter_task_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='Pwd',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='RPwd',
            field=models.CharField(max_length=8),
        ),
    ]
