# Generated by Django 3.2.9 on 2021-11-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0013_auto_20211119_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='Pwd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='RPwd',
            field=models.CharField(max_length=50),
        ),
    ]
