# Generated by Django 3.2.9 on 2021-11-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0015_alter_task_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Age',
            field=models.DateField(),
        ),
    ]
