# Generated by Django 3.2.9 on 2021-11-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0016_alter_task_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=30)),
                ('Age', models.DateField()),
                ('City', models.CharField(max_length=50)),
                ('Pwd', models.CharField(max_length=50)),
                ('RPwd', models.CharField(max_length=50)),
                ('Images', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('Phone', models.CharField(max_length=50)),
            ],
        ),
    ]
