# Generated by Django 3.2.9 on 2021-11-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0017_adminpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpage',
            name='Images',
            field=models.ImageField(blank=True, null=True, upload_to='picss/'),
        ),
    ]
