# Generated by Django 3.2.9 on 2021-11-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0018_alter_adminpage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Images',
            field=models.ImageField(blank=True, default='media\\pics\x08enz.jpg', null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
