# Generated by Django 3.2.9 on 2021-11-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0019_auto_20211123_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Images',
            field=models.ImageField(blank=True, default='pics\x08enz.jpg', null=True, upload_to='pics/'),
        ),
    ]
